### ISSUE TITLE
Running Chapter 3 project code

### ISSUE THREAD

**Issue by satishrao84** [PacktPublishing/Spring5-Design-Patterns#1]
Hi,
The Chapter 3 Dependency Injection project does not have a main in it. 

I was able to mvn clean install successfully, but now how would I run it?

When I go to execute the jar, I get the below error:

> bash-3.2$ java -jar ./target/Chapter-03-Spring-Dependency-Injection-0.0.1-SNAPSHOT.jar

> no main manifest attribute, in ./target/Chapter-03-Spring-Dependency-Injection-0.0.1-SNAPSHOT.jar

Is it possible to run this project even when there's no main class in it?

**Comment by dineshonjava** [comment]
Added main file, thanks
