### ISSUE TITLE
Is this a good book for spring starters?

### ISSUE THREAD

**Issue by iamzhengkai** [PacktPublishing/Spring5-Design-Patterns#3]
Is this book a good one?

**Comment by iamzhengkai** [comment]
I'm new to spring, learned and used spring for a while, want to know more about spring framework. I want to know if this book suit for me.

**Comment by naveens10** [comment]
This book is for developers who would like to use design patterns to address common problems while designing an app using the Spring Framework and Reactive Programming approach. A basic knowledge of the Spring Framework and Java is assumed. 
There are a wide array of books and videos available for beginners on Packt website. Here is the link for Spring MVC Beginner's Guide, https://prod.packtpub.com/in/application-development/spring-mvc-beginners-guide
