### ISSUE TITLE
Small mistake 

### ISSUE THREAD

**Issue by kurenchuksergey** [PacktPublishing/Spring5-Design-Patterns#4]
https://github.com/PacktPublishing/Spring5-Design-Patterns/blob/eae58cd715a4bc873989ef1f51503bdd84871198/Chapter-07-Spring-JDBC-template-pattern/src/com/packt/patterninspring/chapter7/bankapp/callbacks/AccountExtractor.java#L26

new Acount(...) after if :) maybe

**Comment by dineshonjava** [comment]
Thanks for feedback solved
